ptitSeb/box64

README.md
Fix broken link and a typo in Readme.md regarding the x64primop.c
=> Fix broken link and a typo in Readme.md

CMakeLists.txt
On older kernel < 5.X sigcontext.h defines this flag `#ifdef CONFIG_64BIT` which prevents building on some platforms.
Tests where made on Fedora 34 - Nintendo Switch using https://gitlab.com/l4t-community/l4t-kernel-4.9 ( an up to date fork of https://gitlab.com/switchroot/kernel/l4t-kernel-4.9 )
Issue log :
```
/run/media/azkali/SHARE/Workspace/box64/src/libtools/signals.c: In function ‘my_box64signalhandler’:
/run/media/azkali/SHARE/Workspace/box64/src/libtools/signals.c:714:18: error: invalid use of undefined type ‘struct _aarch64_ctx’
714 |         while (ff->magic && !fpsimd) {
|                  ^~
/run/media/azkali/SHARE/Workspace/box64/src/libtools/signals.c:715:18: error: invalid use of undefined type ‘struct _aarch64_ctx’
715 |             if(ff->magic==FPSIMD_MAGIC)
| …
```
=> Fix missing CONFIG_64BIT kernel for older kernel

src/include/myalign.h, src/libtools/signals.c
ppc64le/ELFv2 appears to use the same varargs type as LoongArch64. I changed the loongarch varargs macros to apply to powerpc64 as well, and it builds and appears to work correctly.
The only other change is a small difference in structs between 32 and 64 bit powerpc uc_mcontext.
=> Minor changes to allow box64 to build and run on 64-bit PowerPC.

debian/changelog
The package name is "box86" in changelog and it prevents building .deb packages.
=> Correct package name in Debian changelog

src/libtools/signals.c
uc_link isn't initialized by getcontext(). This may not matter depending on what was previously there, but on ppc64le this is garbage, and test 13 invariably fails. This is a good idea on all platforms anyway and better matches the functional description in the man page.
=> ensure uc_link is properly initialized in getcontext(), fixes ppc64le

CMakeLists.txt, src/custommem.c
Minimal edits to allow building box64 with page size of 64k, I have not reviewed code to see if this change could cause side effects elsewhere. Happy to dig further if necessary, hints welcome.
Tested with build:
$ cmake .. -DRPI4ARM64=1 -DPAGE64K=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
Then execution of a simple hello world program in C, compiled with default compiler:
$ file ../../hello/hello
../../hello/hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=84ad46c4690c1fe8443641401de8c3536bf0c6b8, not stripped
$ ./box64 ../../hello/hello
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:65536
Box64 with Dynarec v0.1.9 826f9cf built on Jun 30 2022 10:09:17
Using …
=> Enable 64k page size

.github/workflows/release.yml
the previous PR changed the order of the preview in the actions dropdown to have the OS first, making it more difficult to read the platform. my bad. this corrects it so that the OS is listed last
see below:
=> change order of matrix (to preview better under checkmark dropdown

CMakeLists.txt
Wrapper filenames were generated by replacing ".c" with "_private.h". Unfortunately this matched anywhere in the string, causing problems if the path contained a directory containing the substring ".c". For instance, if box64 is compiled in a '.cache' directory (as AUR helpers like to do, see #144), the directory name was inadvertently mangled into '_private.hache'.
Fix this by restricting the match to the end of the string.
=> fix overzealous replace in wrappers pathnames

docs/COMPILE.md
How did you built with only 2GB swap?
Here at a file 'dynarec_arm64_00.c' at pass3 is:
total        used        free      shared  buff/cache   available
Mem:          931460      840392       60032          20       31036       50928
Swap:        3135484     2312704      822780
This is at console, on desktop will be worse. Here is not working with only 2GB swap. I don't think GPU memory from 64 MB to 16 MB will make a difference.
=> more swap for rpi3

src/include/signals.h
It does not fully build on alpine (other errors). But i want to check this does not break glibc at least with ci.
=> use sighandler_t instead of __sighandler_t so it compiles for musl

src/main.c
The `sscanf()` needed the first two params swapped to correctly parse the env var.
=> Fixed parameter order for BOX64_DYNAREC_HOTPAGE env parsing.

src/wrapped/wrappedlibx11_private.h
Hit this using libGLX.so from the FEX rootfs.
=> wrap _XAsyncErrorHandler

src/libtools/signals.c
Removed a warning:
```
box64/src/libtools/signals.c:846:6: warning: #warning Unhandled architecture [-Wcpp]
846 |     #warning Unhandled architecture
|      ^~~~~~~
```
=> [RISCV] Get pc from ucontext_t for RV64

src/dynarec/arm64/arm64_lock.S
ref: https://github.com/ptitSeb/box64/commit/3f1c37aa76ff13d90e60eb66c4516f8feebaf3f5#r103714224
=> [ARM64] Fixed a typo in arm64_lock_incif0

debian/rules, docs/COMPILE.md
Debian package maintainers typically prefer using a .zip of the release of software instead of pulling from the master source tree to build their package.
=> add -dnogit=1 flag to debian rules

src/dynarec/rv64/rv64_printer.c, src/dynarec/rv64/rv64_printer.h
For a starter, I added a disassembler for `rv64_print` to work, this should be helpful to debug. Now box64 can decode RISC-V instructions:
```
Jump to next
Table64: 0x36213c50
00000697        auipc   a3, 0
0186b683        ld      a3, 24(a3)
00130313        addi    t1, t1, 1
0006b603        ld      a2, 0(a3)
00030593        addi    a1, t1, 0
000600e7        jalr    ra, 0(a2)
---- END OF BLOCK ---- (1)
```
=> [RV64] Add a disassembler for RV64 instructions

src/dynarec/rv64/dynarec_rv64_00.c, src/dynarec/rv64/dynarec_rv64_emit_shift.c, src/dynarec/rv64/dynarec_rv64_helper.h, src/dynarec/rv64/rv64_emitter.h
test03 and test04 now run without `Dynarec stopped because of Opcode`.
=> [RV64_DYNAREC] Added C1 /(4/6) SHL opcode

.github/workflows/release.yml
If we can pass the environment variable `QEMU_LD_PREFIX=/usr/{riscv64,aarch64}-linux-gnu/lib/`
to ctest, it should also work and be cleaner, but I don't know how to do it as
I am not familiar with cmake.
Note that TEGRAX1 is not currently working because of a mismatch in GLIBC version.
Therefore, we skipped this platform.
=> Enable test for RV64 and ARM64 in CI

docs/COMPILE.md
Installing the keys in the system location will likely cause fallout in upgrades. Install into /etc/apt/trusted.gpg.d where it's commonly expected.
=> docs/COMPILE.md: Use trusted.gpg.d

src/dynarec/arm64/dynarec_arm64_helper.h
I saw @ptitSeb fixed this on the RISC-V port at https://github.com/ptitSeb/box64/commit/b2484afe96ecb2e68150432fd7f8fe05b26dabee, but it's actually copied from ARM side...
=> [ARM64_DYNAREC] Fixed UFLAG_OP12 helper macro

docs/box64.pod
When not installing box64 from git but from a distro package manager (like `apt install box64`) then one expects `man box64` to contain reasonable documentation as the user will not have access to the files from the git repository.
Unfortunately, the format man pages are written in, is quite hard to read and write (I think) so I prepared a manual page in the POD format which can be turned into a man page by running:
pod2man --center "Manual" --release "box64 0.2.2" box64.pod
Maybe CMake should do that conversion?
=> add manual page in pod format

src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_helper.h
Stardew Valley works again, but I haven't found what's wrong with the current implementation of `MINSS`/`MAXSS`.
=> [RV64_DYNAREC] Added 0F BA /4 BT opcode & some fixes 

src/dynarec/rv64/dynarec_rv64_00.c, src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/dynarec_rv64_emit_shift.c, src/dynarec/rv64/dynarec_rv64_f20f.c, src/dynarec/rv64/dynarec_rv64_f30f.c, src/dynarec/rv64/dynarec_rv64_helper.h
Note that Stardew Valley as well as the SSE2 test from simde stopped working after https://github.com/ptitSeb/box64/commit/49a3255a476f0904db2f054d9fba3a6e57b3fbe8. I haven't found the cause yet, but I think it's not a problem with `MOVDQU` itself.
=> [RV64_DYNAREC] Added more opcodes for Stardew Valley

src/dynarec/rv64/dynarec_rv64_emit_math.c
RISC-V does not have `SUBB` or `SUBH` instructions. When using `SUB` or `SUBW`, there are some scenarios where the result will not be sign-extended. It's a bit tricky and hard to spot.
=> [RV64_DYNAREC] Fixed emit_sub8/16

debian/rules
I encountered error when building deb on armbian jammy. After excluding libstdc++.so.5 like [box86](https://github.com/ptitSeb/box86/blob/master/debian/rules#L13) there is no issue when building deb.
=> exclude libstdc++.so.5 in dh_shlibdeps

src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrappedmpg123types.h, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedmpg123.c, src/wrapped/wrappedmpg123_private.h
Also deleted all the `_32` ones, I believe it's copied from box86, and it does not appear in the 64-bit shared library.
=> [WRAPPER] Fixed mpg123 wrapper

src/wrapped/wrappedfontconfig_private.h
I'm trying to run Tencent Meeting (a Zoom-like app popular in China), and these functions are used by it. I also fixed some libxcb/libxcbrandr wrapper functions in https://github.com/ksco/box64/commit/fb5aab53b8f461cf99a7635c2ff6aed5bfe49ce8, but Tencent Meeting still fails to run and I can't find why, so I excluded this commit as it's not verified.
=> [WRAPPER] Added more fontconfig wrapped functions

src/elfs/elfloader.c
`head->path` is used by `FreeElfMemory` when Dyanrec is on. I also moved `h->name` because it looks better.
=> [ELF] Fixed a use-after-free issue

src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_64.c, src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/dynarec_rv64_f30f.c, src/dynarec/rv64/rv64_emitter.h, src/dynarec/rv64/rv64_printer.c
64 33 `XOR Gd, Seg:Ed` is causing black screen in ut2004 and Crypt of the NecroDancer (but sound works), so I commented that section. @ksco and I have no idea about this problem, but this instruction is heavily used in stack protection code and is a bottleneck. @ptitSeb can you look at this?
=> [RV64_DYNAREC] Added more opcodes

src/dynarec/rv64/dynarec_rv64_00_2.c
A few more opcodes added for 7 Billion Humans. This game doesn't run as smoothly as Human Resource Machine and requires an emulated SDL, but it's playable.
=> [RV64_DYNAREC] Added A1/A2/A3 MOV opcodes

wrapperhelper/gen.cpp
This PR adds support for detecting `long` types in the second LLVM helper.
=> Added support for builtin type distinction (long/long long)

src/dynarec/rv64/dynarec_rv64_00_2.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/dynarec_rv64_d9.c, src/dynarec/rv64/dynarec_rv64_db.c, src/dynarec/rv64/dynarec_rv64_dd.c, src/dynarec/rv64/dynarec_rv64_df.c, src/dynarec/rv64/dynarec_rv64_f20f.c, src/dynarec/rv64/dynarec_rv64_f30f.c
Still one more opcode (namely `67 42 88 34 00 mov byte ptr [eax + r8d], sil`) is needed by this game, and `geted32` is necessary for this one. 
@ptitSeb Could you implement it when you have the time?
=> [RV64_DYNAREC] Added more opcodes for Bastion and some fixes

CMakeLists.txt, src/dynarec/rv64/dynarec_rv64_00_2.c, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/dynarec_rv64_d8.c, src/dynarec/rv64/dynarec_rv64_dc.c, src/dynarec/rv64/dynarec_rv64_dd.c, src/dynarec/rv64/dynarec_rv64_helper.h
The game seems running fully in Dynarec now.
=> [RV64_DYNAREC] Added more opcode for Unciv and some fixes

src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedmpg123_private.h, wrapperhelper/README.md
Added for this game: https://cyfo.itch.io/katkoot, only `mpg123_info` is needed, by I added others anyway.
I used wrapperhelper, with this command under x86-64: `./helper /usr/include/mpg123.h libmpg123 x64 x64 --`
It throws me a bunch of errors, and some mpg123 function wrappers are missing, don't know what's wrong.
```
--------------- Libclangtooling parse complete -----------------
input.cc:2:25: error: brackets are not allowed here; to declare an array, place the brackets after the name
double[2][576] xr[2];
~~~~~~~~      ^
[2][576]
input.cc:3:25: error: brackets are not allowed here; to declare an array, place the brackets after the name
double[2][22] sfb[2];
~~~~~~~       ^
[2][22]
input.cc:4:27: error: brackets are not allowed here; to declare an array, place the brackets after the …
```
=> Added some mpg123 wrapped functions

src/dynarec/rv64/dynarec_rv64_660f.c
Fixes luajit error in https://github.com/ptitSeb/box64/issues/763. The gameplay works now.
=> [RV64_DYNAREC] Fixed 66 0F 3A 0B ROUNDSD opcode

src/wrapped/wrappedlibx11_private.h
It's the only 1 symbol that is missing for Cassette Beasts to work.
=> Added 1 libx11 symbol for #758

src/main.c
if box_dynarec = 0 before free context, it will not execute box_free for jump table.
More details are in file src/custommem.c around in line 1506.
=> [DYNAREC] Fix jump table not free on exit

src/dynarec/rv64/dynarec_rv64_helper.c
=> [RV64_DYNAREC] Forget mmx float reg only needed

src/dynarec/rv64/dynarec_rv64_660f.c, system/box64.box64rc
Cached by cosim when running dav1d 1.2.0. I believe that dav1d did not work yesterday because of this reason, because I also ran cosim yesterday, and it also reported inconsistent results for this opcode. But I can't reproduce the problem that dav1d prints a bunch of error logs and then exits abnormally.
=> [RV64_DYNAREC] Fixed 66 0F 38 2B PACKUSDW opcode

src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedwaylandclient_private.h
Added for [Telegram](https://desktop.telegram.org/), but it still not working (segfaulted).
=> [WRAPPER] Added some wayland function wrappers

src/dynarec/rv64/dynarec_rv64_helper.c
I noticed this issue when trying to run a Java game called Mindustry. The generated code for `67 8D LEA Gd, Ed` is not right, and I find that it's caused by geted32. I haven't looked at how `ED32` should be decoded, but I'm guessing it should be the same as `ED`, except for the imm part. So I just fixed `geted32` by comparing it to `geted`, and it seems to work.
=> [RV64_DYNAREC] Fixed geted32

src/dynarec/rv64/dynarec_rv64_00_1.c
Caught by cosim when trying to run Overcooked! 2 (Unity). But the game still not working. Unity games seem generally not working.
```
Found path: /home/ksco/Documents/Overcooked! 2/Overcooked2.x86_64
Using emulated /home/ksco/Documents/Overcooked! 2/Overcooked2_Data/Mono/x86_64/libmono.so
Mono path[0] = '/home/ksco/Documents/Overcooked! 2/Overcooked2_Data/Managed'
Mono config path = '/home/ksco/Documents/Overcooked! 2/Overcooked2_Data/Mono/etc'
25295|SIGBUS @0x378f068c (???(0x378f068c)) (x64pc=0x102b25c25//home/ksco/Documents/Overcooked! 2/Overcooked2_Data/Mono/x86_64/libmono.so:"/home/ksco/Documents/Overcooked! 2/Overcooked2_Data/Mono/x86_64/libmono.so + 0xd5bf4", rsp=0x101ffdf20, stack=0x101800000:0x102000000 own=(nil) fp=0x2c0160), for accessing 0x2c0052 (code=1/prot=7), …
```
=> [RV64_DYNAREC] Fixed 6B IMUL opcode

src/dynarec/arm64/dynarec_arm64_0f.c, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_helper.c
1. We cannot use xRAX as a return value register when using `call_c`, it will be "restored" after the c function returns.
2. `div64` and `div32` sets `xRDX`, so even if `xRDX` is a callee-saved register, we still need to save & restore it.
=> [DYNAREC] Fixed call_c issues

src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_64.c
Also replaced `LUI(x3, 0xffffffffffff0);` with `LUI(x3, 0xffff0);`, which is more readable IMO.
=> [DYNAREC_RV64] Fixed 9x SETcc opcodes

src/emu/x64run660f.c
=> [INTERPRETER] Added 66 0F 38 37 PCMPGTQ opcode

src/emu/x64run_private.c
The base address needs to wrap around at 32 bits before being converted to a pointer.
=> [32BITS] Use 32-bit types to compute 32-bit addresses.

docs/COMPILE.md
Newer generic  arm builds on my repo will be under the package name `box64-arm64`.
=> Update package name in COMPILE.md

src/main.c
On Debian there are the packages libstdc++6-amd64-cross and libgcc-s1-amd64-cross which provide amd64 shared libraries which are usually used for cross compiling without multiarch but using a sysroot prefix instead. Since libgcc_s.so.1 and libstdc++.so.6 shipped by these packages are fully functional, let box64 use them as a fallback if it cannot find them in the other paths that it searched before.
=> add /usr/x86_64-linux-gnu/lib to the shared library search path

src/emu/x64run.c
This is just a start, as I "almost" managed to run VARA.exe on wine/hangover with box64 in WoW64, but not there yet. But with this change (same I need to run VARA.exe on box86) I got a bit ahead in the tests.
The debug info:
http://abradig.org.br/hermes/debug.txt
=> Allow running at NULL, and trigger a segfault (backport from box86 5cdc1b9fa2238938e49176fcd937a1294c55a03d )

src/dynarec/rv64/rv64_emitter.h, src/include/debug.h, src/main.c, src/rv64detect.c
On LicheePi 4A, it now outputs:
```
Dynarec for RISC-V With extension: I M A F D C XTheadBa XTheadBb XTheadBs XTheadCondMov XTheadMemIdx XTheadMemPair XTheadFMemIdx XTheadMac PageSize:4096 Running on unknown riscv64 cpu with 4 Cores
```
Next step is to actually use these instructions.
=> [RV64_DYNAREC] Added thead vendor extension detection

.github/workflows/release.yml, src/dynarec/rv64/rv64_emitter.h
xthead extensions require qemu 8.1.0, therefore not available in CI
=> [CI] Test RISCV with bit-manipulation extensions on

src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_f30f.c, src/dynarec/rv64/rv64_emitter.h
also reverted a falsy optimization introduced in #989, and now StardewValley works again.
=> [RV64_DYNAREC] Added more support for XTheadBs extension

src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h
Introduced in #1021. Maybe we should disable the `function_list` generator in CI to catch this kind of issue.
=> [WRAPPER] Added missing function signature

src/wrapped/wrappedlibc.c
Try on the second time with MAP_FIXED if addr is not 0. Encountered this on RISC-V with wine 8.18, maybe help #1031 too. thanks @ptitSeb for the help!
=> [WRAPPER] Fixed my_mmap64 on MAP_FIXED handling, helps wine 8.18

src/elfs/elfloader.c
=> [ELFLOADER] Fixed align issue (may help #1057)

src/dynarec/dynarec_native_pass.c
x1 is the second parameter when calling native functions in GO_TRACE, so we cannot use it as a scratch register for xthead optimization.
After this, cosim is working again on LPi4A.
=> [COSIM] Fix GO_TRACE

src/custommem.c
This gives a slight performance increase to applications like Steam on devices with only 4GB ram
=> Change blokc size to 64kb

src/dynarec/rv64/dynarec_rv64_emit_math.c
`andn` is `rs1 & ~rs2`. @ptitSeb can you test if this fixes the wine issue on VF2?
=> [RV64_DYNAREC] Fixed zbb andn optimization

src/dynarec/rv64/dynarec_rv64_emit_shift.c
Found this while reviewing xFlags usage.
=> [DYNAREC_RV64] Fixed emit_ror32

src/emu/x64runf30f.c, src/libtools/threads.c
=> [ANDROID] Fix Clang Compiling

src/dynarec/arm64/dynarec_arm64_emit_shift.c
For the SHR instruction, the OF flag is set to the most-significant bit of the original operand.
=> fix emit_shr16

src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_66.c, src/dynarec/rv64/dynarec_rv64_660f.c
66 0F BD BSR seems to trigger some unknown bugs in other opcodes.
=> [DYNAREC_RV64] Added more opcodes for VMP-protected GI

CMakeLists.txt
=> [CMakelist] Remove a "#"

src/dynarec/rv64/dynarec_rv64_660f.c
After tedious bisecting with BOX64_NODYNAREC, I found that this opcode was not correctly implemented. However, a strange SIGBUS error pops up when I'm trying to run YuanShen.exe (Genshin Impact) with this patch. If the fix is only applied to VMP areas (by checking `addr` in dynarec), the program can produce a meaningful "A debugger has been found running in your system.\nPlease, unload it from memory and restart your program." message instead of garbage as before.
=> [RV64_DYNAREC] Fixed 66 0F B6 MOVZX opcode

src/custommem.c, src/include/custommem.h, src/include/rbtree.h, src/libtools/signals.c, src/mallochook.c, src/tools/rbtree.c, src/wrapped/wrappedlibc.c
Some protections are in fact 32 bits wide (`PROT_GROWSDOWN`, `PROT_GROWSUP`). This PR reverts the narrowing to an 8-bit integer for the memory tracking (fixes *maybe* #1200 and similar issues).
=> [RBTREE] Reverted memory tracking to 32 bits

src/dynarec/rv64/dynarec_rv64_66.c
=> [RV64_DYNAREC] Fixed 66 87 XCHG opcode

docs/box64.pod, src/main.c
When set, box64 will only print its version and then exit. This option is analogous to QEMU_VERSION used by binfmt_misc emulation of qemu-user. Its purpose is the same: provide a way to soft-disable binfmt_misc emulation as well as for identifying box64 as the registered binfmt_misc emulator.
This commit enables adding support for box64 to the arch-test utility. With this change, arch-test is able to soft-disable box64 as the x86_64 emulator in the same way as it does this for qemu and wine already. Without this change, arch-test will report an architecture as natively executable by the processor, disregarding that it actually gets emulated by box64.
Furthermore, this commit enables identifying box64 as the currently registered emulator for x86_64. This way, applications that know that …
=> When BOX64_VERSION is set, just print the version and exit

src/wrapped/generated/wrapper.c
This PR finishes @xctan's fix (#1227) by rebuilding the wrapper files, hich have not been regenerated since (`rm src/wrapper/generated/functions_list.txt && make WRAPPERS`).
=> [WRAPPER] Regenerated the wrapper files

src/wrapped/wrappedcap_private.h, src/wrapped/wrappedlibxcbrandr_private.h
These functions are needed for SteamVR's vrcompositor and vrcompositor-launcher to run.
=> more wrapped functions in libxcb-randr and libcap

src/dynarec/la64/dynarec_la64_emit_math.c, src/dynarec/la64/dynarec_la64_helper.c, src/dynarec/la64/dynarec_la64_helper.h, src/dynarec/la64/la64_emitter.h
Unlike RISC-V, the imm part in `ANDI`/`ORI`/`XORI` on LoongArch is zero-extended instead of sign-extended, thus the F_OF2 trick is unnecessary.
cc @factfinding
=> [LA64_DYNAREC] Removed F_OF2 trick as it's unnecessary

src/emu/x64run_private.c, src/wrapped/wrappedlibc.c
The asterisk is placed outside the neighbor parentheses.
References:
1. https://elixir.bootlin.com/glibc/glibc-2.39/source/csu/libc-start.c#L209
2. https://cdecl.org/?q=int+*%28main%29+%28int%2C+char+**%2C+char+**%29
3. https://cdecl.org/?q=int+%28*main%29+%28int%2C+char+**%2C+char+**%29
=> [WRAPPER] Fixed a typo in the signature of my___libc_start_main

CMakeLists.txt, src/dynarec/arm64/arm64_immenc.c, src/dynarec/arm64/arm64_immenc.h
This PR adds a function that encodes an immediate value into an integer packing various opcode fields when possible, and returns `0` otherwise.
The lowest 6 bits encode the rotation (`immr`), the next 6 encode the size/pattern (`imms`), the next bit encodes the `N` bit and the next one (`0x2000`) encodes whether the immediate given is encodable (`1`) or not (`0`).
=> [ARM] Added immediate encoding

src/dynarec/arm64/dynarec_arm64_f30f.c
`VDUP_16` duplicates 16-bit element from the low qword of v1, which is not what we want.
Fixes #1342
=> [ARM64_DYNAREC] Fixed a falsy optimization on PSHUFHW

src/dynarec/arm64/dynarec_arm64_00.c, src/dynarec/arm64/dynarec_arm64_66.c, src/dynarec/arm64/dynarec_arm64_67.c, src/dynarec/arm64/dynarec_arm64_emit_shift.c, src/dynarec/la64/dynarec_la64_00.c, src/dynarec/la64/dynarec_la64_emit_shift.c, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_66.c, src/dynarec/rv64/dynarec_rv64_67.c, src/dynarec/rv64/dynarec_rv64_emit_shift.c
Use the same "pattern" on all similar opcodes across all 3 backends.
=> [DYNAREC] Made shift operations handle count==0 more uniformly

.github/workflows/manual.yml, .github/workflows/release.yml
The older version of these workflows use an old version of Node.js, this brings in the current versions.
=> Update GH-Actions workflows to remove Node.js deprecation warning.

src/dynarec/rv64/dynarec_rv64_66.c
Copy-paste is the new way of code review. This issue can be traced back to the very beginning, but we discovered it only now, and not through debugging.
=> [RV64_DYNAREC] Fixed 66 C7 MOV opcode

src/dynarec/la64/dynarec_la64_emit_math.c, src/dynarec/rv64/dynarec_rv64_emit_math.c
A very subtle error, the source register does not guarantee that the high bits are clean. Found while trying to run the program in #1450 on RV64.
=> [DYNAREC] Fixed CF flag computation

src/dynarec/rv64/dynarec_rv64_helper.h
This is already handled by `CALL_` above.
=> [RV64_DYNAREC] Remove useless code

src/dynarec/rv64/dynarec_rv64_helper.c
Machine: Pioneer Box
Error log as follows:
=> [RV64_DYNAREC] Fix SIGABRT handling in x87cache testing

src/dynarec/la64/dynarec_la64_emit_math.c, src/dynarec/la64/dynarec_la64_emit_shift.c, src/dynarec/la64/la64_emitter.h
Most are ported from RV64 fixes, but one of them is LA64-specific.
=> [LA64_DYNAREC] Fixed some non-lbt flags comutation issues

docs/box64.pod
The `docs/box64.pod` file now renders an error:
=> Fix unclosed item list

docs/box64.pod
According to https://github.com/ptitSeb/box64/blob/ab9f848dcd8ab4b5e73aad22934eb47fae39252f/docs/USAGE.md#L7 , the config file path should be `/etc/box64.box64rc`
=> Fix typo on box64 config file

CMakeLists.txt, src/custommem.c, src/custommmap.c
As you suggested, I added a barebones custommap.c file and it passes compilation and linking in my buildroot GCC 13.3 cross-compilation toolchain to arm64 / rv64.
It can probably be tidied up.
=> Try to fix mmap64 already defined error in custommem.c

docs/COMPILE.md
closes https://github.com/ptitSeb/box64/issues/1576
at pi-apps we have been using our own apt repo which is better maintained and we keep strict rules of not breaking old installs (eg: through package renaming or otherwise). this has been the case for a year now. Our efforts (including both Ryan and Itai) are consolidated in these repos that we all have access to.
=> switch to maintained Pi-Apps-Coders apt repo

src/wrapped/wrappedwaylandclient.c, src/wrapped/wrappedwaylandclient_private.h, src/wrapped/wrappedxkbregistry_private.h
This was a late-night attempt to fix issue #1581.
I still don't really know how the wrappings work (I should take time and learn) so I just did what seemed right. For `size_t` and `bool` I guessed how they are specified ('L' and 'c'??).
Unsuprisingly, it does not work at this point! Now there is a SIGILL during/after mapping winewayland.so.
=> Add missing wrappings for winewayland.so

src/core.c, src/include/debug.h, src/rv64detect.c
Dynarec for RISC-V With extension: I M A F D C Zba Zbb Zbc Zbs Vector PageSize:4096 Running on Spacemit(R) X60 with 8 Cores
=> [RV64_DYNAREC] Detect vector extension

src/elfs/elfload_dump.c, src/elfs/elfloader.c, src/elfs/elfloader_private.h, src/elfs/elfparser.c, src/emu/x64int3.c, src/include/elfload_dump.h, src/include/elfloader.h
Fixes #1623 
Reference: https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dynamic-link.h;h=83d834ecaf609082506d161b9744a2b476469b5e;hb=HEAD#l153
=> Handle `.relr.dyn` section

src/dynarec/la64/dynarec_la64_private.h, src/dynarec/rv64/dynarec_rv64_private.h
4b0b3fc98ae4a1e848765e0cd48f958a13fc683d introduced a new function called `get_first_jump_addr`. And I found my machine (cross-compile for riscv64) failed to compile it, because the function declaration was missing for rv64 and la64.
I have no ideas why the CI passed at that time, but I believe we had better add these function declaration.
=> Add missing func declaration: `get_first_jump_addr`

src/core.c, src/include/fileutils.h, src/tools/fileutils.c, src/wrapped/wrappedlibc.c
Many programs (e.g. busybox, ex, bash) can have different behaviors on different `argv[0]`. We should only resolve the `argv[0]` (program name)  to its absolute path but not realpath, i.e. don't resolve the symlinks.
=> Should not follow symlinks on `argv[0]` path resolution

src/dynarec/rv64/dynarec_rv64_helper.c
Should fix #1649. This was removed in 4f229629c007d65b505a72dbac66eb0e686ee312 (by mistake I believe), this PR adds it back.
=> Set last_ip to an unclean state at the end of CALL 

src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/rv64_emitter.h
=> Mask `rs2` when using `bext` instruction if `rex.w` is not set

src/dynarec/rv64/dynarec_rv64_private.h
If I am doing the correct thing, this could closes #1661 .
=> Remove the flags adjustment in `GO_TRACE` for RISC-V 64

src/dynarec/dynarec_native.c
This PR fixes an issue which may appear if an instruction with non-zero `ymm0_out` jumps to the first instruction of a block.
=> [DYNAREC] Fixed `ymm0_purge` for some instructions

src/dynarec/rv64/rv64_lock.S, src/dynarec/rv64/rv64_lock.h
Since rv64_lock_cas_dq is removed, we should also remove its global symbol declaration and its prototype. Otherwise, we get and undefined symbol reference, which breaks ELF checks that some distros employ.
Fixes: 9dbd7fc7e0615f48c9287305610bf9aed1cc24f3
=> [RV64_DYNAREC] Cleanup for removed rv64_lock_cas_dq

src/dynarec/rv64/dynarec_rv64_helper.c
We cannot use `FSD` here, because RISC-V uses Nan-boxing on single precision floating point values, so if some freg holds a float value, the high 32bits will be all 1s.
=> [RV64_DYNAREC] Clear high 32bits when write back as single

src/dynarec/rv64/dynarec_rv64_helper.c
This may be a bit confusing, but we don't really need to clear the upper bits here, it's already cleared for opcodes like movss, and for others, the upper bits should be retained.
=> [RV64_DYNAREC] Fixed GETGXSS_empty on upper bits handling

src/core.c, src/include/debug.h, src/rv64detect.c
We require VLEN >= 128 for the convenience of implementing SSE 2/3/4 opcodes, this PR checks it.
=> [RV64_DYNAREC] Added vlen detection

CMakeLists.txt, src/dynarec/la64/dynarec_la64_00.c, src/dynarec/rv64/dynarec_rv64_00_3.c
Added missing code from commit 2e6acc86e15927cbfa416b94a226494aae84662d, also disabled test21_android, we need someone to compile it.
=> [DYNAREC] Fixed CI failures for RV64 and LA64

.github/workflows/release.yml, src/dynarec/rv64/dynarec_rv64_660f_vector.c, src/dynarec/rv64/dynarec_rv64_helper.c, src/dynarec/rv64/dynarec_rv64_helper.h, src/dynarec/rv64/rv64_emitter.h
For vlen>128, we cannot use load/store whole vector instructions! Sorry for this mistake. This PR replaced all the whole vector load/stores with the normal ones, which requires the `vtype` to be set correctly using `SET_ELEMENT_WIDTH()`.
=> [RV64_DYNAREC] Fixed vector infra

src/core.c
There are still issues in the vector infra(see https://github.com/ptitSeb/box64/issues/1703#issuecomment-2296328685), disable it for now until it's ready for the enduser...
=> [RV64_DYNAREC] Disable vector extension by default until it's ready

docs/COMPILE.md, docs/USAGE.md, docs/box64.pod, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_660f.c, src/dynarec/rv64/dynarec_rv64_f0.c, src/dynarec/rv64/dynarec_rv64_helper.c, src/dynarec/rv64/dynarec_rv64_helper.h, src/dynarec/rv64/dynarec_rv64_private.h, src/dynarec/rv64/rv64_emitter.h, src/dynarec/rv64/rv64_prolog.S
Fix some typos in docs and dynarec/rv64
=> [RV64_DYNAREC] Fix some typos in docs and dynarec/rv64

src/dynarec/rv64/rv64_printer.c
Rewrote rv64_printer to be more maintainable, and fully supported the following extensions:
```
rv_a
rv_d
rv_f
rv_i
rv_m
rv_v
rv_zba
rv_zbb
rv_zbc
rv_zicsr
rv_zbs
rv64_a
rv64_d
rv64_f
rv64_i
rv64_m
rv64_zba
rv64_zbb
rv64_zbs
```
Xthead* extensions will be the next.
=> [RV64_DYNAREC] Refactored rv64_printer

src/include/khash.h, src/librarian/library.c
WPS Presentation can be run on RISC-V Lichee Pi 4A with the power of box64. And I did profiling for it, in order to find the performance bottleneck. The profiling result is shown below:
So I investigated why `getSymbolInSymbolMaps` (`kh_get_symbolmap` & `kh_get_symbol2map`) costs so much. I found that `getSymbolInSymbolMaps` calls `kh_get` 6 times at the worst case, and the most expensive calculation in `kh_get` is "hashing". Symbols are strings and current string hashing function needs to traversal the whole string.
My idea is to eliminate the duplicate "hashing", since the pass-in symbol name does not change during `getSymbolInSymbolMaps`.
The optimization is straightforward. That is, just calculate the hash once and reuse the result. To achieve this, I added two APIs called `kh_hash` & …
=> Eliminate duplicate hash calculations for `getSymbolInSymbolMaps`

wrapperhelper/Makefile, wrapperhelper/README.md, wrapperhelper/example-libc.h, wrapperhelper/src/generator.c, wrapperhelper/src/generator.h, wrapperhelper/src/lang.c, wrapperhelper/src/lang.h, wrapperhelper/src/main.c, wrapperhelper/src/parse.c, wrapperhelper/src/preproc.c
This PR:
- greatly improves the output of the wrapper helper, by not changing ignored lines;
- should make the Makefile compatible on more platforms (using fd redirection instead of `|&`);
- implements some more features in the parser (`inline` and `_Noreturn`);
- allows for explicit type mapping (using the `#pragma wrappers type-letters` pragma), for example mapping `FILE*` to type letter `S`
=> Better wrapper helper

wrapperhelper/src/generator.c, wrapperhelper/src/lang.c, wrapperhelper/src/lang.h, wrapperhelper/src/machine.c, wrapperhelper/src/machine.h, wrapperhelper/src/parse.c, wrapperhelper/src/preproc.c
This PR fixes the preprocessor handling for `#elif`/`#else` blocks and moves the type validation function to `machine.c`, along with an extra `machine_t` parameter, which allows for per-architecture handling of type size and content validation.
This PR is mainly preparing for the wrapper helper to work with `box32`.
=> [WRAPPERHELPER] Fixed preprocessor logic, moved type validation to machine

src/dynarec/arm64/dynarec_arm64_private.h, src/dynarec/la64/dynarec_la64_private.h, src/dynarec/rv64/dynarec_rv64_functions.c, src/dynarec/rv64/dynarec_rv64_helper.c, src/dynarec/rv64/dynarec_rv64_pass0.h, src/dynarec/rv64/dynarec_rv64_pass1.h, src/dynarec/rv64/dynarec_rv64_pass2.h, src/dynarec/rv64/dynarec_rv64_pass3.h, src/dynarec/rv64/dynarec_rv64_private.h
Separated `dyn->insts[ninst].vector_sew` to `_entry` and `_exit` to simplify the initialization process, also it's better for the dump log.
Related PR: #1819 
Related Issue: #1818
=> [RV64_DYNAREC] Refactored vector SEW tracking

src/dynarec/rv64/dynarec_rv64_0f_vector.c, src/dynarec/rv64/dynarec_rv64_660f_vector.c, src/dynarec/rv64/dynarec_rv64_helper.c, src/dynarec/rv64/dynarec_rv64_helper.h, src/dynarec/rv64/dynarec_rv64_pass2.h, src/dynarec/rv64/dynarec_rv64_pass3.h, src/dynarec/rv64/rv64_emitter.h
About the fix: when there is a reset at `reset_n`, the current `sew` should be reset to current `sew@entry` instead of `sew@exit`, obviously.
Related Issue: #1818
=> [RV64_DYNAREC] Added 1 more opcode for vector and some refactor and fixes too

wrapperhelper/README.md, wrapperhelper/example-libc.h, wrapperhelper/include-override/aarch64/stdc-predef.h, wrapperhelper/src/cstring.c, wrapperhelper/src/cstring.h, wrapperhelper/src/generator.c, wrapperhelper/src/generator.h, wrapperhelper/src/lang.c, wrapperhelper/src/lang.h, wrapperhelper/src/main.c, wrapperhelper/src/parse.c, wrapperhelper/src/preproc.c
This PR:
- adds a file specific to ARM64 (to be revisited), with the list of all predefined macros;
- fixes a fatal error when an argument of a function, other than the last one, is an array;
- adds back explicitly simple structures;
- adds strict conversion and changes `type_letters` to be relaxed conversion (which doesn't care about qualifiers);
- change the default behaviour on the generator to always add an `E` character when the function is a `GO[W]M`;
- adds more supported casts in expression evaluation;
- removes "Warning: '...' is already in the declaration map with the same type"
=> Improve the wrapper helper

wrapperhelper/example-libc.h, wrapperhelper/src/parse.c
This PR moves the `#pragma wrappers` in `example-libc.h` into the `parse.c` file, i.e. adds predefined mark-simple structures (`glob_t`...) and conversions (`FILE*` is `S`, `xcb_connection_t*` is `b`).
=> [WRAPPERHELPER] Added predefined mark-simple and conversions

wrapperhelper/include-override/aarch64/bits/pthreadtypes-arch.h, wrapperhelper/include-override/aarch64/stdc-predef.h, wrapperhelper/include-override/common/stdc-predef.h, wrapperhelper/include-override/x86_64/bits/pthreadtypes-arch.h, wrapperhelper/include-override/x86_64/stdc-predef.h, wrapperhelper/src/generator.c, wrapperhelper/src/generator.h, wrapperhelper/src/lang.c, wrapperhelper/src/machine.c, wrapperhelper/src/machine.h, wrapperhelper/src/parse.c
This PR fixes some bugs in the parser (every keywords in expressions were replaced by `sizeof`, some `nrefs` were not updated correctly, wrong variable name in a `kh_end`), fixes some other memory issues (use-before-init, double free on deletion...), and adds partial multi-architecture support (if a difference between the types is detected, the type is simply not converted).
=> [WRAPPERHELPER] Fixed some bugs, added partial multiarch support

wrapperhelper/Makefile
This PR updates the `wrapperhelper/Makefile` to also include `log.c`, and remove the analysis of the generator file which speeds up build time.
=> [WRAPPERHELPER] Forgot to add the Makefile

src/dynarec/arm64/arm64_emitter.h, src/dynarec/arm64/dynarec_arm64_helper.c, src/dynarec/la64/dynarec_la64_helper.c, src/dynarec/rv64/dynarec_rv64_helper.c, src/dynarec/rv64/rv64_emitter.h
This PR pushed the CALL/RET optimization even further. The idea is to utilize the Return Address Stack or RAS in the hardware.
For example, on AArch64, for x86 `CALL`, emit `BLR`, and for x86 `RET`, emit `RET LR`. This would hint the hardware to push the return address onto the RAS for x86 `CALL` and pop and compare the return address for x86 `RET`.
Other changes are there to prevent unrelated indirect jumps from polluting the RAS.
=> [DYNAREC] Tweaking indirect jumps for CALL/RET to use the return address stack

src/dynarec/arm64/dynarec_arm64_00.c, src/dynarec/arm64/dynarec_arm64_64.c, src/dynarec/arm64/dynarec_arm64_67.c, src/dynarec/la64/dynarec_la64_00.c, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/rv64_prolog.S
Related PR: #1907 
For out of block jumps, instead of jump to the table directly, add one more jump to make the RAS optimization valid.
A simple benchmark as below shows this fixes the performance loss in out-of-block-jumps introduced in PR #1907, while keeps the in-block-jumps as fast.
```
#include <limits.h>
int foo(int a) {
return a + a;
}
int bar(int a) {
return a + 2;
}
int baz(int a) {
return a + 3;
}
int indirect_version(int (*fn)(int), int (*fn2)(int), int (*fn3)(int)) {
int i, b = 0;
for (i = 0; i < INT_MAX >> 2; ++i) {
b += fn(b) + fn2(b) - fn3(b);
}
return b;
}
int main(int argc, char *argv[]) {
return indirect_version(&foo, &bar, &baz);
}
```
=> [DYNAREC] Optimized CALL/RET RAS for out of dynablock jumps

src/dynarec/rv64/dynarec_rv64_helper.c, src/libtools/my_x11_xevent.c
Resolved a compilation error due to variable declaration within a switch-case statement without enclosing braces. 
This error occurred with older GCC compilers, which require declarations to be part of a block within switch-case constructs.
=> Fix compilation error in my_x11_xevent.c (#1938) and  dynarec_rv64_helper.c

wrapperhelper/Makefile, wrapperhelper/src/generator.c, wrapperhelper/src/main.c, wrapperhelper/src/prepare.c, wrapperhelper/src/prepare.h, wrapperhelper/src/preproc.c, wrapperhelper/src/vector.c, wrapperhelper/src/vector.h
This PR adds support for `#pragma once` in the wrapper helper, reducing the number of errors; it also fixes a duplicated line in the Makefile causing a link-time error, improves a bit the box32-mode output, and ignores newlines in macro expansions. This allows `openssl/ssl.h` to be parsed correctly.
=> [WRAPPERHELPER] Better wrapper helper

src/box64context.c, src/custommem.c, src/include/box64context.h, src/include/rbtree.h, src/tools/rbtree.c
Red-black tree operations now consistently use the `rbtree_` prefix, and internal functions remain unexposed. Tested on RV64GC, resulting in a 498-byte reduction in the `.text` section size.
=> [RBTREE] Unify naming and prevent unintended symbol exposure

src/core.c, src/dynarec/rv64/dynarec_rv64_00_0.c, src/dynarec/rv64/dynarec_rv64_00_2.c, src/dynarec/rv64/dynarec_rv64_00_3.c, src/dynarec/rv64/dynarec_rv64_0f.c, src/dynarec/rv64/dynarec_rv64_64.c, src/dynarec/rv64/dynarec_rv64_66.c, src/dynarec/rv64/dynarec_rv64_67.c, src/dynarec/rv64/dynarec_rv64_emit_logic.c, src/dynarec/rv64/dynarec_rv64_emit_math.c, src/dynarec/rv64/dynarec_rv64_emit_shift.c, src/dynarec/rv64/dynarec_rv64_emit_tests.c, src/dynarec/rv64/dynarec_rv64_helper.h
A small (~3%) performance improvement was observed in coremark.
=> [RV64_DYNAREC] Made eflags emulation branchless with xtheadcondmov

src/dynarec/arm64/arm64_emitter.h, src/dynarec/arm64/dynarec_arm64_00.c
This PR significantly improves the performance of spinlocks on Apple M2, but has no effects on the D2000.
Test program:
```c
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <fenv.h>
#include <stdio.h>
#include <pthread.h>
#include <emmintrin.h>
void spin_lock(int *p)
{ 
while(!__sync_bool_compare_and_swap(p, 0, 1)) {
__builtin_ia32_pause();
}
}
void spin_unlock(int volatile *p)
{
asm volatile ("":::"memory");
*p = 0;
}
#define NUM_THREADS 10
#define NUM_ITERATIONS 2000000
int lock = 0;
int counter = 0;
void* increment_counter(void* arg) {
for (int i = 0; i < NUM_ITERATIONS; ++i) {
spin_lock(&lock);
counter++;
spin_unlock(&lock);
}
return NULL;
}
int main() {
pthread_t threads[NUM_THREADS];
for (int i = 0; i < NUM_THREADS; ++i) {
if (pthread_create(&threads[i], NULL, …
```
=> [ARM64_DYNAREC] Generate corresponding hint instruction for PAUSE

src/dynarec/arm64/arm64_emitter.h, src/dynarec/arm64/arm64_printer.c, src/dynarec/arm64/dynarec_arm64_00.c
This should fix the performance regression in #2064.
=> [ARM64_DYNAREC] Use YIELD instead of WFE

wrapperhelper/src/lang.c, wrapperhelper/src/main.c, wrapperhelper/src/parse.c
This PR adds the `--gst` option to the wrapper helper, which automatically marks every structure starting with `_G` and ending with `Class` as simple.
This option is very rough in its current state, and may not be very usable. Note that the behavioural change is completely removed if `--gst` is not provided when running the binary.
=> Add the '--gst' option to the wrapper helper

src/dynarec/la64/dynarec_la64_00.c, src/dynarec/la64/dynarec_la64_66.c, src/dynarec/la64/dynarec_la64_67.c, src/dynarec/la64/dynarec_la64_f0.c, src/dynarec/la64/dynarec_la64_helper.h
Hi,
Passed testcase for `SBB Gb, Eb`:
```
#include <stdio.h>
#include <stdint.h>
#include <assert.h>
void test_sbb8(uint8_t n, uint8_t m, uint8_t expected_al, uint8_t expected_dl) {
uint8_t al;
uint8_t dl;
__asm__ __volatile__ (
"movb  %[n], %%dl\n" 
"movb  %[m], %%al\n" 
"subb  %[m], %%al\n" 
"sbbb  %[n], %%dl\n" 
".byte 0x1A\n"                   // SBB Gb, Eb
".byte 0xCA\n" 
"movb  %%al, %[al]\n" 
"movb  %%dl, %[dl]\n" 
: [al] "=r" (al), [dl] "=r" (dl)
: [n] "r" (n), [m] "r" (m)
: "al", "dl", "memory");
printf("al=0x%x\n", al);
printf("dl=0x%x\n", dl);
assert(al == expected_al && dl == expected_dl);
}
int main(int argc, char* argv[]) {
test_sbb8(0x1, 0x0, 0x0, 0x0);
}
```
Thanks,
Leslie Zhai
=> [LA64_DYNAREC] Added SBB opcodes

wrapperhelper/src/parse.c
This PR adds support for empty declarations in the wrapper helper.
=> [WRAPPERHELPER] Accept and ignore semicolons instead of declarations

wrapperhelper/src/generator.c
This PR fixes a bug where, if the reference file marks a simple data symbol as a function, the generator will segfault.
=> [WRAPPERHELPER] Transform from function to data if needed

src/dynarec/la64/dynarec_la64_660f.c, src/dynarec/la64/dynarec_la64_helper.h, src/dynarec/la64/la64_emitter.h
Hi,
[dav1d benchmark](https://archive.fosdem.org/2021/stands.fosdem.org/stands/box86/performances/):
```
./dav1d -i Chimera-AV1-8bit-480x270-552kbps.ivf --muxer null
```
before:
```
Decoded 8929/8929 frames (100.0%) - 3.67/23.98 fps (0.15x)
real	40m35.251s
user	40m20.151s
```
after:
```
Decoded 8929/8929 frames (100.0%) - 89.06/23.98 fps (3.71x)
real	1m40.299s
user	1m39.578s
```
Thanks,
Leslie Zhai
=> [LA64_DYNAREC] Added more 660F opcodes

docs/USAGE.md, src/core.c, src/dynarec/dynarec_arch.h, src/dynarec/dynarec_native_pass.c, src/dynarec/la64/dynarec_la64_00.c, src/dynarec/la64/dynarec_la64_0f.c, src/dynarec/la64/dynarec_la64_64.c, src/dynarec/la64/dynarec_la64_66.c, src/dynarec/la64/dynarec_la64_660f.c, src/dynarec/la64/dynarec_la64_67.c, src/dynarec/la64/dynarec_la64_emit_logic.c, src/dynarec/la64/dynarec_la64_emit_math.c, src/dynarec/la64/dynarec_la64_emit_shift.c, src/dynarec/la64/dynarec_la64_emit_tests.c, src/dynarec/la64/dynarec_la64_f0.c, src/dynarec/la64/dynarec_la64_f30f.c, src/dynarec/la64/dynarec_la64_functions.c, src/dynarec/la64/dynarec_la64_functions.h, src/dynarec/la64/dynarec_la64_helper.c, src/dynarec/la64/dynarec_la64_helper.h, src/dynarec/la64/dynarec_la64_pass0.h, src/dynarec/la64/dynarec_la64_private.h, src/dynarec/la64/la64_emitter.h, src/dynarec/la64/la64_printer.c, src/dynarec/rv64/dynarec_rv64_emit_tests.c, src/tools/rcfile.c
The `7z b` result is quite interesting, `nativeflags` alone and `lbt` alone has basically the same score, which makes LBT existence a bit awkward. :smile: 
```
BOX64_DYNAREC_NATIVEFLAGS=1 box64 ./7z b
Compressing  |                  Decompressing
Dict     Speed Usage    R/U Rating  |      Speed Usage    R/U Rating
KiB/s     %   MIPS   MIPS  |      KiB/s     %   MIPS   MIPS
22:      11992   572   2040  11667  |     166101   791   1792  14168
23:      13197   667   2015  13447  |     150168   726   1790  12995
24:      11584   625   1994  12456  |     161201   787   1798  14148
25:      12455   690   2061  14221  |     158073   780   1804  14068
----------------------------------  | ------------------------------
Avr:             638   2028  12948  |              771   1796  13845
Tot: …
```
=> [LA64_DYNAREC] Added nativeflags support

src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrappedlibctypes.h, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedlibc.c, src/wrapped/wrappedlibc_private.h
On some newer architectures, like LoongArch, there is no `sysctl()` symbol.
=> [WRAPPED] Always return ENOSYS in the deprecated sysctl

src/dynarec/la64/dynarec_la64_0f.c, src/dynarec/la64/dynarec_la64_660f.c
=> [LA64_DYNAREC] Added MOVLPD and MOVHPD opcodes

src/core.c, src/dynarec/la64/dynarec_la64_0f.c, src/dynarec/la64/la64_emitter.h, src/emu/x64emu.c, src/tools/my_cpuid.c
```
ksco@aosc [ ~ ] $ box64 -v
Dynarec for LoongArch with extension LSX LASX LBT_X86 LAM_BH LAMCAS SCQ PageSize:4096 Running on Loongson-3A6000-HV with 8 cores
Will use hardware counter measured at 2.5 GHz
```
=> [LA64_DYNAREC] Added hardware wall-clock support

docs/USAGE.md, docs/box64.pod, src/core.c, src/dynarec/arm64/dynarec_arm64_functions.c, src/dynarec/dynarec_native.c, src/dynarec/la64/dynarec_la64_functions.c, src/dynarec/rv64/dynarec_rv64_functions.c, src/include/debug.h, src/include/dynarec_native.h
Hi,
To find out DynaRec jit "hot" code:
```
perf record -e cpu-cycles box64 scimark4-x64
```
scimark:  https://math.nist.gov/scimark2/download_c.html
Before no perf map no Symbol:
```
Samples: 133K of event 'cpu-cycles:u', Event count (approx.): 66380844254
Overhead  Command       Shared Object          Symbol
2.38%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c3888
2.35%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c388c
1.18%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c62ec
1.14%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c62fc
0.96%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c62ac
0.94%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c0c7c
0.88%  scimark4-x64  perf-19878.map         [.] 0x000000fff42c0c6c
0.82% …
```
=> [DYNAREC] Implement perf map

docs/COMPILE.md
Include a note for users utilizing environments
where only the box64 binary is available.
This addition ensures that users can install
the necessary libraries before running box64.
=> [DOCS] Improve cross-build instructions

src/core.c, src/dynarec/arm64/dynarec_arm64_functions.c, src/dynarec/dynarec_native.c, src/dynarec/la64/dynarec_la64_functions.c, src/dynarec/rv64/dynarec_rv64_functions.c, src/include/dynarec_native.h
Hi,
To find benchmark some workload high branch-misses:
```
export BOX64_DYNAREC_PERFMAP=1
perf record -e branches -e branch-misses box64 scimark4-x64
```
To find Symbol `0x000000fff5417170` around:
```
Samples: 22K of event 'branch-misses:u', Event count (approx.): 225354432
Overhead  Command       Shared Object          Symbol
29.42%  scimark4-x64  perf-22759.map         [.] 0x000000fff5417174
29.02%  scimark4-x64  perf-22759.map         [.] 0x000000fff5417170
```
There might be some opportunity to reduce the branch-misses:
```
...
0xfff5417160 2 Random_nextDouble:TEST Ed, Gd
0xfff5417168 4 Random_nextDouble:CMOVS Gd, Ed
0xfff5417178 1 Random_nextDouble:TEST Ed, Gd
0xfff541717c 1 Random_nextDouble:MOV Ed, Gd
...
```
Thanks,
Leslie Zhai
=> [DYNAREC] Appended instruction name to symbol

src/wrapped/wrappedlibc_private.h
Hi,
before:
```
Error: Symbol monstartup not found, cannot apply R_X86_64_JUMP_SLOT @0x3f096d4ef0 (0x4b346) in /yourpath/x64.so
Error: relocating Plt symbols in elf x64.so
Error initializing needed lib /yourpath/x64.so
Exception in thread "main" java.lang.ExceptionInInitializerError: initialization failed with java.lang.UnsatisfiedLinkError: /yourpath/x64.so: Cannot dlopen("/yourpath/x64.so"/0xffec4ba3b0, 1)
```
after:
work :)
Thanks,
Leslie Zhai
=> [WRAPPED] Added monstartup

.github/workflows/release.yml
Not sure what changed, but `libglib2.0-dev` is a requirement now.
=> [CI] Fixed xuantie-qemu build

src/dynarec/arm64/dynarec_arm64_avx_66_0f38.c, tests/test30.c
Just like 0x8c, I've made changes to the relevant code to avoid accessing out-of-bounds memory when a portion of the mask is 0.
I added the test case but commented it out, I don't think I should tamper with ref30.txt and the binary file test30.
=> fix VPMASKMOV and VMASKMOVP

src/wrapped/wrappedlibc.c
Hi,
Linux kernel 5.11 (February, 2021) added the epoll_pwait2 system call, but LA64 ABI 1.0 kernel is 4.19.0, so `epoll_pwait2` is not available.
Thanks,
Leslie Zhai
=> Fix undefined reference to `epoll_pwait2' for LA64 ABI 1.0

src/wrapped/wrappedandroidshmem_private.h, src/wrapped/wrappedlibc_private.h, src/wrapped/wrappedvulkan_private.h
Two of these commits are Android specific.
The Vulkan one seems to be related to newer releases of Wine - without it, Vulkan is completely broken.
Re-opened a new one since I found a bunch of new stuff that needs to be added.
=> [WRAPPER] missing functions and features

wrapperhelper/src/preproc.c
This PR fixes the parsing of headers with code such as:
```c
#define bug(...)
bug(1, 2)
```
in the wrapper helper. The bug is due to a double-free of all arguments after the implicit `__VA_LIST__` argument.
=> Fixed a bug in the wrapper helper due to variadic arguments

src/dynarec/la64/dynarec_la64_0f.c, src/dynarec/la64/dynarec_la64_660f.c
Optimize MAXPD/MAXPS.
use cLT (~cLT = un eq gt), then reverse selection.
=> [LA64_DYNAREC] Optimize la64 MAXPD/MAXPS.

src/wrapped/wrappedlibc.c
Box64 segfaults on this call. I updated it in accordance with the specification in the header file:
```
GOM(epoll_ctl, iFEiiip)
GOM(epoll_pwait, iFEipiip)
GOM(epoll_pwait2, iFEipipp)
GOM(epoll_wait, iFEipii)
```
With this change an example program ran successfully.
On a side note, why wasn't this typo detected by the script validating the wrappers?
=> Corrected arguments of my_epoll_pwait2

src/wrapped32/wrappedlibc.c, src/wrapped32/wrappedlibc_private.h
The change was tested with that snippet of code:
```c
#include <time.h>
#include <stdio.h>
int main() {
time_t timestamp;
time(&timestamp);
struct tm *info = localtime(&timestamp);
printf("%s", asctime(info));
timestamp = 52921504606846977ll;
info = localtime(&timestamp);
printf("%s", asctime(info));
timestamp = 9589934592ll;
info = localtime(&timestamp);
printf("%s", asctime(info));
}
```
Compiled with `i686-linux-gnu-gcc -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 sample.c`.
=> Add __localtime64 and __time64 in box32 mode

src/dynarec/rv64/dynarec_rv64_0f.c
maskmovq write when sign bit == 1.
if mask byte = 0x00, should skip.
replace BLT with BLE.
found this issue when testing mmx for la64.
unittest at https://github.com/phorcys/x64_inst_test/blob/main/mmx/test_mmx_maskmovq.c
=> [RV64_DYNAREC] fix MASKMOVQ

src/tools/rbtree.c
By caching boundary nodes, we eliminate the need for repeated traversal.
Cached nodes are updated only during insertions or deletion, via simple assignments.
To test this approach, I ran chess.exe with box64 and wine (same config as in https://github.com/ptitSeb/box64/issues/2511).
The result: 397 full tree traversals were avoided, thanks to just 607 lightweight cache updates during approximately 3,500 tims insertions.
The performance impact is expected to be even greater in larger or more complex workloads.
The function `add_range()` was only called when `tree->root == NULL`.  
In such cases, the internal while-loop never executes, and the call simply forwards to:
```c
add_range_next_to(tree, NULL, start, end, data);
```
=> [RBTREE] Cache boundary nodes and remove `add_range()` 

src/tools/rbtree.c
This PR fixes an edge case in `rb_unset`, where unsetting a range `start:end` with a node overlapping from the left would not unset the overlap:
```
before
+--------+---------+
|   42   | (unset) |
+--------+---------+
^ start       ^ end
after (bug)
+--------+---------+
|   42   | (unset) |
+--------+---------+
^ start       ^ end
after (fixed)
+----+-------------+
| 42 |   (unset)   |
+----+-------------+
^ start       ^ end
```
=> Fixed an edge case in `rb_unset`

CMakeLists.txt, src/dynarec/la64/dynarec_la64_66.c, src/dynarec/la64/dynarec_la64_66f30f.c, src/dynarec/la64/dynarec_la64_f30f.c, src/dynarec/la64/dynarec_la64_helper.h, src/dynarec/la64/la64_emitter.h
* 66.f3.0f.b8/bc/bd POPCNT/TZCNT/LZCNT 16bits ops
* f3.0f.bd LZCNT
* fix f3.0f.bc TZCNT (GETED/RESTORE_EFLAGS x1 conflict)
=> [LA64_DYNAREC] Add POPCNT/TZCNT/LZCNT ops.

src/tools/bridge.c
`NewBrick()` currently uses `setProtection()` after `box_mmap()`, which fails to mark the region with the `MEM_MMAP` label. As a result, `getMmapped()` returns 0, even though the memory was allocated via mmap.
=> Use `setProtection_mmap` in `NewBrick`

docs/COMPILE.md
Previously the README only mentioned `-DARM_DYNAREC=1`. 
CMakeLists.txt also defines `RV64_DYNAREC` and `LARCH64_DYNAREC`, so this expands the docs to list all dynamic-recompilation flags.
=> [DOCS] Include RV64 and LARCH64 DynaRec options

docs/COMPILE.md
Sorry I missed the line breaks earlier — replaced improper ones 
with two trailing spaces to ensure correct formatting.
=> [Docs] Fix the format of Commit 816c4bd

docs/USAGE.md, docs/box64.pod, docs/gen/gen.py, docs/gen/usage.json, src/emu/x64syscall.c, src/emu/x86syscall_32.c, src/include/env.h
Thanks @sehraf for the checker (#2631), I added and improved most of the missing things. Now the checker outputs:
```
BOX64_LD_PRELOAD              : missing env.h entry
```
... which is fine as this one is special and not managed by the env module.
Important changes:
1. `BOX64_MMAP32` is now enabled by default.
2. `BOX64_FUTEX_WAITV` is removed, only configurable at compilation time.
=> [DOCS] Align usage.json and env.h

src/tools/env.c
`BOX64_EMULATED_LIBS=libfake.so gdb --args ./box64.real --help`
```
Program received signal SIGSEGV, Segmentation fault.
AddPath (path=path@entry=0x7fffffcbf8 "libfake.so", collection=collection@entry=0x20, 
folder=folder@entry=0) at ./src/tools/pathcoll.c:91
91      ./src/tools/pathcoll.c: 没有那个文件或目录.
(gdb) bt
#0  AddPath (path=path@entry=0x7fffffcbf8 "libfake.so", collection=collection@entry=0x20, 
folder=folder@entry=0) at ./src/tools/pathcoll.c:91
#1  0x0000000034870154 in AppendList (collection=0x20, List=<optimized out>, folder=folder@entry=0)
at ./src/tools/pathcoll.c:141
#2  0x0000000034874050 in applyCustomRules () at ./src/tools/env.c:193
#3  0x0000000034878530 in LoadEnvVariables () at ./src/tools/env.c:624
#4  0x0000000034831f20 in initialize (argc=2, argv=0x7fffffe028, …
```
=> fix: env BOX64_EMULATED_LIBS triggers sigsegv

src/include/rbtree.h
I used `grep -rnw . -e 'rbtree_init('` to discover that there are seven red-black trees, and the information in `rbtree.h` is out of date. This PR:
- Remove outdated information
- Document the seven red-black trees that Box64 currently uses:
1. memprot
2. mapallmem
3. blockstree
4. db_sizes
5. envmap
6. rbt_dynmem
7. volatileRanges
- Clarify each tree's role
- Notes the trade-offs of using the bitmap allocator (`map128_customMalloc`), which allocates 128-byte slabs and results in internal fragmentation
Note: I'm not sure I fully understand the rules and behavior of `envmap`, so feedback or corrections on that part would be appreciated.
=> [RBTREE] Update comments on red-black tree usage

src/dynarec/la64/dynarec_la64_avx_0f.c, src/dynarec/la64/dynarec_la64_avx_66_0f.c, src/dynarec/la64/dynarec_la64_avx_66_0f3a.c, src/dynarec/la64/dynarec_la64_avx_f2_0f.c, src/dynarec/la64/dynarec_la64_avx_f3_0f.c
*  VEX.0f           VMOVNTPS/VLDMXCSR/VSTMXCSR
*  VEX.66.0f      VMOVNTPD/VMOVD/VMOVNTDQ
*  VEX.66.0f.3a VMOVNTDQA
*  VEX.f2.0f       VMOVDDUP/VLDDQU
*  VEX.f3.0f       VMOVSLDUP/VMOVSHDUP/VMOVD
LA64 avx load/store  patches series contain 4 patch
1.  misc
2.  movhps/d,movlps/d
3.  maskmov
4.  movzx/movsx
This is patch 1, misc load/store ops.
My x64 insts unittest could be used for testing those ops:
https://github.com/phorcys/x64_inst_test
=> [LA64_DYNAREC] Add la64 avx load/store ops part 1.

src/dynarec/la64/dynarec_la64_avx_66_0f38.c
Use vext2xv to opt movsx/movzx.
For VEX.128 bw,wd,dq ops, use vsllwil(latency 2) instead of vext2xv (latency 3) .
Old imp use xvsllwil is wrong, because xvsllwil operate on per 128bits channel. 
But MOVSX/MOVZX VEX.256 ops only read src operand from low 128bits.
=> [LA64_DYNAREC] Fix/Opt la64 avx movsx/movzx ops.

src/dynarec/la64/dynarec_la64_660f.c, src/dynarec/la64/dynarec_la64_avx_66_0f.c, src/dynarec/la64/dynarec_la64_avx_66_0f38.c, src/dynarec/la64/dynarec_la64_avx_66_0f3a.c, src/dynarec/la64/la64_emitter.h, src/dynarec/la64/la64_printer.c
Fix 66.0F.F3 PSLLQ
Fix VEX.66.0F.7E VMOVD not zero-extend
Fix Vex.66.0F.3A.06 VPERM2F128/VPERM2I128
Fix Vex.66.0F.3A.0D VBLENDPD
Fix VEX.66.0F.3A.18/38 VINSERTF128/VINSERTI128  when q0 == q1 or q0 == q2 
Fix VEX.66.0F.3A.21 VINSERTPS fix u8 get pos
Fix VEX.66.0F.3A.40 VDPPS Fix VREPLVEIxy emit when vex.l 
Fix VEX.66.0F.38.0C VPERMILPS
Fix VEX.66.0F.38.2B VPACKUSDW
Fix VEX.66.0F.38.93 VGATHERQPD
=> [LA64_DYNAREC] Fix some la64 avx/sse ops.

src/tools/rbtree.c
Add a fast-path in `rb_get()` and `rb_get_64()` that checks the tree’s cached `leftmost->start` and `rightmost->end` bounds before calling `find_addr()`. If the query address lies outside the address bounds, we return 0 immediately, avoiding an unnecessary tree walk.
This mirrors the idea used in [jserv/rbtree](https://github.com/jserv/rbtree/blob/d3e6d6d6b6b1d297642606a5e199108ba7fc19f0/rbtree.c#L881)’s `rb_cached_contains()`, using cached min/max to short-circuit lookups.
Behavior is unchanged (both functions still return 0 when not found); only negative lookups become cheaper.
=> Add O(1) early-out to eusing cached bounds in `rb_get()` and `rb_get_64()`

src/dynarec/la64/dynarec_la64_0f.c, src/dynarec/la64/dynarec_la64_emit_logic.c
Fix B3 BTR eflags when cpuext.lbt == 1. 
Fix 16bits AND when cpuext.lbt ==1.
=> [LA64_DYNAREC] Fix BTR , ANDW opcode.
